// Generated by CoffeeScript 1.7.1
(function() {
  var blacklist, converted, e, files, fs, helpers, original, path, why, wrench, _;

  path = require('path');

  fs = require('fs-extra');

  wrench = require('wrench');

  _ = require('lodash');

  helpers = require('./helpers');

  original = "../famous";

  converted = "../famous-commonjs";

  blacklist = [".git"];

  try {
    wrench.rmdirSyncRecursive(converted);
  } catch (_error) {
    e = _error;
    if (e.message.indexOf("ENOENT") !== 0) {
      throw e;
    }
  }

  fs.mkdir(converted);

  files = fs.readdirSync(original);

  _.each(files, function(file) {
    var inPath, outPath;
    if (_.contains(blacklist, file)) {
      return;
    }
    inPath = path.join(original, file);
    outPath = path.join(converted, file);
    console.log("Copying " + inPath + " to " + outPath);
    return fs.copySync(inPath, outPath);
  });

  debugger;

  why = 7;

}).call(this);
